# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: |
      echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
      sudo apt-get update && install ncbi-blast+ samtools muscle 
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
      source "${HOME}/miniconda/etc/profile.d/conda.sh"
      export PATH="${HOME}/miniconda/bin:$PATH"
    command: echo 'start script'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
